name: Deploy Flask App to GHCR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug - List Repository Files
        run: ls -l

      - name: Debug - Check GitHub Secrets
        run: echo "Using GitHub secret: ${{ secrets.GHCR_PAT }}"

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
       docker buildx build --platform linux/amd64 --progress plain --tag ghcr.io/$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')/devsecops-ci-cd:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')/devsecops-ci-cd:latest

